# Site settings
title: XB Blog
SEOTitle: 张庆君的博客 | XB Blog
header-img: img/post-bg-rwd.jpg
email: zhangqingjun920@outlook.com
description: "XB Blog."
keyword: "BY, XB Blog, 张庆君的博客, NewStart, 张庆君"
url: "https://zhangqingjun920.github.io/"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/zhangqingjun920/zhangqingjun920.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "八百里云和月"
sidebar-avatar: /img/about-me-first.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
zhihu_username:     JUNICE
weibo_username:     雨沉默XB
github_username:    zhangqingjun920



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
# gitalk:
#   enable: true    #是否开启Gitalk评论
#   clientID: Ov23liVY2e8CLc78K2ZS                            #生成的clientID
#   clientSecret: f3f4a08f225a2095438f9e9e0dc5a8f932687d3e    #生成的clientSecret
#   repo: zhangqingjun920.github.io    #仓库名称
#   owner: zhangqingjun920    #github用户名
#   admin: zhangqingjun920
#   distractionFreeMode: true #是否启用类似FB的阴影遮罩
#   #labels: [“Gitalk”,"study"]

  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css">
  <script src="https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js"></script>

  <div id="gitalk-container"></div>
  
  var gitalk = new Gitalk({
  clientID: Ov23liVY2e8CLc78K2ZS
  clientSecret: f3f4a08f225a2095438f9e9e0dc5a8f932687d3e
  repo: zhangqingjun920.github.io
  owner: zhangqingjun920
  admin: zhangqingjun920
  # id: location.pathname,      // Ensure uniqueness and length less than 50
  distractionFreeMode: true  // Facebook-like distraction free mode
})

# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 2              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "XHS-LZ",
        href: "https://www.xiaohongshu.com/user/profile/5ea135c10000000001003e92"
    },{
        title: "XHS-LWW",
        href: "https://www.xiaohongshu.com/user/profile/638378ba000000001f01b987"
    },{
        title: "XHS-XB",
        href: "https://www.xiaohongshu.com/user/profile/655e197f000000000202ad57"
    },{
        title: "DY-XB",
        href: "https://v.douyin.com/EU2k7lTMqNs/ 8@3.com "
    }
]
